package org.feeluown.mobile

import kotlinx.serialization.Serializable

@Serializable
data class NavigationFeature(
    val id: String,
    val providerId: String,
    val providerName: String,
    val title: String,
    val category: String,
    val contentType: String,
    val requiresLogin: Boolean,
)

@Serializable
data class NavigationTrack(
    val id: String,
    val title: String,
    val artists: String,
    val album: String,
    val source: String,
    val sourceType: String,
    val coverUrl: String? = null,
    val durationMs: Long? = null,
    val localUri: String? = null,
    val localDirectoryId: String? = null,
    val lyrics: String? = null,
    val providerId: String? = null,
    val providerName: String? = null,
    val isSmartReplacement: Boolean = false,
    val originalId: String? = null,
    val originalTitle: String? = null,
    val originalArtists: String? = null,
    val originalAlbum: String? = null,
    val originalSource: String? = null,
    val originalProviderName: String? = null,
    val originalCoverUrl: String? = null,
    val replacementId: String? = null,
    val replacementTitle: String? = null,
    val replacementArtists: String? = null,
    val replacementAlbum: String? = null,
    val replacementSource: String? = null,
    val replacementProviderName: String? = null,
    val replacementCoverUrl: String? = null,
    val replacementStrategy: String? = null,
    val replacementScore: Double? = null,
    val isUnavailable: Boolean = false,
    val artistItemId: String? = null,
    val albumItemId: String? = null,
    val artistItems: List<NavigationMediaItem> = emptyList(),
    val providerUrl: String? = null,
    val providerTags: List<String> = emptyList(),
)

@Serializable
data class NavigationPlaylist(
    val id: String,
    val title: String,
    val providerId: String,
    val providerName: String,
    val coverUrl: String? = null,
    val description: String = "",
    val playCount: Long? = null,
    val providerUrl: String? = null,
    val trackCount: Int? = null,
    val isOwnedByCurrentUser: Boolean? = null,
    val isSubscribed: Boolean? = null,
    val canAddTracks: Boolean? = null,
    val canRemoveTracks: Boolean? = null,
    val canDelete: Boolean? = null,
)

@Serializable
data class NavigationMediaItem(
    val id: String,
    val title: String,
    val providerId: String,
    val providerName: String,
    val type: String,
    val coverUrl: String? = null,
    val description: String = "",
    val providerUrl: String? = null,
    val trackCount: Int? = null,
    val albumCount: Int? = null,
)

@Serializable
data class NavigationVideo(
    val id: String,
    val title: String,
    val artists: String,
    val providerId: String,
    val providerName: String,
    val coverUrl: String? = null,
    val durationMs: Long? = null,
    val providerUrl: String? = null,
)

fun ProviderFeature.toNavigationFeature(): NavigationFeature = NavigationFeature(
    id = id,
    providerId = providerId,
    providerName = providerName,
    title = title,
    category = category.name,
    contentType = contentType.name,
    requiresLogin = requiresLogin,
)

fun NavigationFeature.toProviderFeature(): ProviderFeature = ProviderFeature(
    id = id,
    providerId = providerId,
    providerName = providerName,
    title = title,
    category = ProviderFeatureCategory.valueOf(category),
    contentType = ProviderContentType.valueOf(contentType),
    requiresLogin = requiresLogin,
)

fun MusicTrack.toNavigationTrack(): NavigationTrack = NavigationTrack(
    id = id,
    title = title,
    artists = artists,
    album = album,
    source = source,
    sourceType = sourceType.name,
    coverUrl = coverUrl,
    durationMs = durationMs,
    localUri = localUri,
    localDirectoryId = localDirectoryId,
    lyrics = lyrics,
    providerId = providerId,
    providerName = providerName,
    isSmartReplacement = isSmartReplacement,
    originalId = originalId,
    originalTitle = originalTitle,
    originalArtists = originalArtists,
    originalAlbum = originalAlbum,
    originalSource = originalSource,
    originalProviderName = originalProviderName,
    originalCoverUrl = originalCoverUrl,
    replacementId = replacementId,
    replacementTitle = replacementTitle,
    replacementArtists = replacementArtists,
    replacementAlbum = replacementAlbum,
    replacementSource = replacementSource,
    replacementProviderName = replacementProviderName,
    replacementCoverUrl = replacementCoverUrl,
    replacementStrategy = replacementStrategy,
    replacementScore = replacementScore,
    isUnavailable = isUnavailable,
    artistItemId = artistItemId,
    albumItemId = albumItemId,
    artistItems = artistRefs.map(MediaRef::toNavigationMediaItem),
    providerUrl = providerUrl,
    providerTags = providerTags,
)

fun NavigationTrack.toMusicTrack(): MusicTrack = MusicTrack(
    id = id,
    title = title,
    artists = artists,
    album = album,
    source = source,
    sourceType = TrackSourceType.valueOf(sourceType),
    coverUrl = coverUrl,
    durationMs = durationMs,
    localUri = localUri,
    localDirectoryId = localDirectoryId,
    lyrics = lyrics,
    providerId = providerId,
    providerName = providerName,
    isSmartReplacement = isSmartReplacement,
    originalId = originalId,
    originalTitle = originalTitle,
    originalArtists = originalArtists,
    originalAlbum = originalAlbum,
    originalSource = originalSource,
    originalProviderName = originalProviderName,
    originalCoverUrl = originalCoverUrl,
    replacementId = replacementId,
    replacementTitle = replacementTitle,
    replacementArtists = replacementArtists,
    replacementAlbum = replacementAlbum,
    replacementSource = replacementSource,
    replacementProviderName = replacementProviderName,
    replacementCoverUrl = replacementCoverUrl,
    replacementStrategy = replacementStrategy,
    replacementScore = replacementScore,
    isUnavailable = isUnavailable,
    artistItemId = artistItemId,
    albumItemId = albumItemId,
    artistItems = artistItems.map(NavigationMediaItem::toMediaRef),
    providerUrl = providerUrl,
    providerTags = providerTags,
)

fun ProviderPlaylist.toNavigationPlaylist(): NavigationPlaylist = NavigationPlaylist(
    id = id,
    title = title,
    providerId = providerId,
    providerName = providerName,
    coverUrl = coverUrl,
    description = description,
    playCount = playCount,
    providerUrl = providerUrl,
    trackCount = trackCount,
    isOwnedByCurrentUser = isOwnedByCurrentUser,
    isSubscribed = isSubscribed,
    canAddTracks = canAddTracks,
    canRemoveTracks = canRemoveTracks,
    canDelete = canDelete,
)

fun NavigationPlaylist.toProviderPlaylist(): ProviderPlaylist = ProviderPlaylist(
    id = id,
    title = title,
    providerId = providerId,
    providerName = providerName,
    coverUrl = coverUrl,
    description = description,
    playCount = playCount,
    providerUrl = providerUrl,
    trackCount = trackCount,
    isOwnedByCurrentUser = isOwnedByCurrentUser,
    isSubscribed = isSubscribed,
    canAddTracks = canAddTracks,
    canRemoveTracks = canRemoveTracks,
    canDelete = canDelete,
)

fun NavigationMediaItem.toProviderMediaItem(): ProviderMediaItem = ProviderMediaItem(
    id = id,
    title = title,
    providerId = providerId,
    providerName = providerName,
    type = ProviderMediaItemType.valueOf(type),
    coverUrl = coverUrl,
    description = description,
    providerUrl = providerUrl,
    trackCount = trackCount,
    albumCount = albumCount,
)

fun MediaRef.toNavigationMediaItem(): NavigationMediaItem = NavigationMediaItem(
    id = id,
    title = title,
    providerId = sourceId,
    providerName = sourceName,
    type = type.name,
    coverUrl = coverUrl,
    description = description,
    providerUrl = externalUrl,
    trackCount = trackCount,
    albumCount = albumCount,
)

fun NavigationMediaItem.toMediaRef(): MediaRef = MediaRef(
    id = id,
    title = title,
    providerId = providerId,
    providerName = providerName,
    type = MediaRefType.valueOf(type),
    coverUrl = coverUrl,
    description = description,
    providerUrl = providerUrl,
    trackCount = trackCount,
    albumCount = albumCount,
)

fun ProviderVideo.toNavigationVideo(): NavigationVideo = NavigationVideo(
    id = id,
    title = title,
    artists = artists,
    providerId = providerId,
    providerName = providerName,
    coverUrl = coverUrl,
    durationMs = durationMs,
    providerUrl = providerUrl,
)

fun NavigationVideo.toProviderVideo(): ProviderVideo = ProviderVideo(
    id = id,
    title = title,
    artists = artists,
    providerId = providerId,
    providerName = providerName,
    coverUrl = coverUrl,
    durationMs = durationMs,
    providerUrl = providerUrl,
)